name: Update Contributors

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-contributor:
    if: ${{ contains(github.event.comment.body, '@all-contributors') }}
    runs-on: ubuntu-latest
    steps:
      - name: Add contributor via bot
        uses: all-contributors/app-bot-action@v1
